apiVersion: v1
kind: Service
metadata:
  name: config-service-04
  labels:
    app: config-service-04
spec:
  type: ClusterIP
  selector:
    app: config-service-04
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
